# -*- coding: utf-8 -*-
"""Starter Code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G3xct475mfdmZFBraP3QbVLxf0HbvivB

Below is the starting code that includes the data pipeline functions. You should focus on writing unit tests for these functions using the unittest framework.
"""

import pandas as pd
import unittest

def data_extraction(file_path):
    data = pd.read_csv(file_path)
    return data

def data_transformation(data):
    data = data.drop_duplicates()
    data['billing_amount'] = data['billing_amount'].str.replace('$', '').astype(float)
    data['total_charges'] = data['billing_amount'] + data['tax_amount']
    return data

def data_loading(data, output_file):
    data.to_csv(output_file, index=False)

class TestDataPipeline(unittest.TestCase):
    def test_data_extraction(self):
        # Write your test cases for data_extraction function here

    def test_data_transformation(self):
        # Write your test cases for data_transformation function here

    def test_data_loading(self):
        # Write your test cases for data_loading function here

if __name__ == '__main__':
    unittest.main()